environment: "development"

server:
  host: "0.0.0.0"
  port: 8080

database:
  url: "postgres://user:password@localhost/nexaagents"
  max_connections: 10

auth:
  jwt_secret: "supersecretkey"
  jwt_expiration: 24 # 24 hours

agora:
  host: "0.0.0.0"
  port: 8081

logging:
  level: "info"
