environment: "development"

server:
  host: "0.0.0.0"
  port: 8080

database:
  url: "postgres://user:password@localhost/nexaagents"
  max_connections: 10

auth:
  jwt_secret: "supersecretkey"
  jwt_expiration: 24 # 24 hours

agora:
  host: "0.0.0.0"
  port: 8081

logging:
  level: "info"

llm:
  provider_name: "LM Studio"
  api_key: ""
  model: "local"
  temperature: 0.7
  max_tokens: 2048
  url: "http://localhost:1234"
  available_models:
    - "local"
    - "llama2"
    - "mistral"
  default_model: "local"
