server:
  host: "0.0.0.0"
  port: 8080
  workers: 4

database:
  url: "postgres://user:password@localhost/nexaagents"
  max_connections: 10

auth:
  jwt_secret: "supersecretkey"
  token_expiry: 3600 # 1 hour in seconds

logging:
  level: "info"
